#!/usr/bin/env python3
"""Generate race-aware server speech data from ESM dialogue voice records."""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
import subprocess


DIAL_RE = re.compile(r'^Record: DIAL "(.*)"$')
INFO_RE = re.compile(r"^Record: INFO ")
RACE_RECORD_RE = re.compile(r'^Record: RACE "(.*)"$')
RACE_RE = re.compile(r'^\s+Race: "(.*)"$')
GENDER_RE = re.compile(r"^\s+Gender: (\d+)")
SOUND_RE = re.compile(r"^\s+Sound File: (.*)$")


def esmtool_dump(esmtool: pathlib.Path, source: pathlib.Path, *record_types: str) -> list[str]:
    command = [str(esmtool)]
    for record_type in record_types:
        command.extend(["-t", record_type])
    command.extend(["dump", str(source)])
    result = subprocess.run(command, check=True, capture_output=True, text=True, errors="replace")
    return result.stdout.splitlines()


def collect_races(esmtool: pathlib.Path, sources: list[pathlib.Path]) -> set[str]:
    races: set[str] = set()
    for source in sources:
        for line in esmtool_dump(esmtool, source, "RACE"):
            match = RACE_RECORD_RE.match(line)
            if match:
                races.add(match.group(1).strip().lower())
    return races


def collect_voice_records(
    esmtool: pathlib.Path,
    sources: list[pathlib.Path],
    allowed_races: set[str],
    sound_prefixes: list[str],
) -> list[tuple[str, str | None, str, str]]:
    records: list[tuple[str, str | None, str, str]] = []
    for source in sources:
        dialogue: str | None = None
        in_info = False
        race: str | None = None
        gender: str | None = None
        sound: str | None = None

        def flush() -> None:
            nonlocal in_info, race, gender, sound
            normalized_race = race.strip().lower() if race else None
            if (
                in_info
                and dialogue
                and normalized_race in allowed_races
                and sound
                and any(sound.lower().startswith(prefix.lower()) for prefix in sound_prefixes)
                and sound.lower().endswith(".mp3")
            ):
                records.append((normalized_race, gender, dialogue.strip().lower(), sound.strip()))
            in_info = False
            race = None
            gender = None
            sound = None

        for line in esmtool_dump(esmtool, source, "DIAL", "INFO"):
            match = DIAL_RE.match(line)
            if match:
                flush()
                dialogue = match.group(1)
                continue
            if INFO_RE.match(line):
                flush()
                in_info = True
                continue
            if not in_info:
                continue
            match = RACE_RE.match(line)
            if match:
                race = match.group(1)
                continue
            match = GENDER_RE.match(line)
            if match:
                gender = match.group(1)
                continue
            match = SOUND_RE.match(line)
            if match:
                sound = match.group(1)
        flush()
    return records


def audio_index(data_roots: list[pathlib.Path]) -> set[str]:
    paths: set[str] = set()
    for root in data_roots:
        sound_root = root / "Sound"
        if not sound_root.is_dir():
            sound_root = root / "sound"
        if not sound_root.is_dir():
            continue
        for path in sound_root.rglob("*"):
            if path.is_file():
                paths.add(path.relative_to(sound_root).as_posix().lower())
    return paths


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(
    voice_sources: list[pathlib.Path],
    records: list[tuple[str, str | None, str, str]],
) -> str:
    grouped: dict[str, dict[str, dict[str, set[str]]]] = collections.defaultdict(
        lambda: collections.defaultdict(lambda: collections.defaultdict(set))
    )
    for race, esm_gender, speech_type, path in records:
        # TES3 dialogue conditions use 0 for male and 1 for female. A missing
        # gender condition makes the voice valid for either player gender.
        genders = ("male",) if esm_gender == "0" else ("female",) if esm_gender == "1" else ("female", "male")
        for gender in genders:
            grouped[race][gender][speech_type].add(path)

    lines = [
        "-- Generated by scripts/generate_server_speech_data.py; do not edit by hand.",
        "-- Voice records: " + ", ".join(source.name for source in voice_sources),
        "local M = {}",
        "",
        "M.races = {",
    ]
    for race in sorted(grouped):
        lines.append(f"    [{lua_quote(race)}] = {{")
        for gender in ("female", "male"):
            gender_data = grouped[race].get(gender)
            if not gender_data:
                continue
            lines.append(f"        [{lua_quote(gender)}] = {{")
            for speech_type in sorted(gender_data):
                lines.append(f"            [{lua_quote(speech_type)}] = {{")
                for index, path in enumerate(sorted(gender_data[speech_type], key=str.lower), start=1):
                    lines.append(f"                {{{lua_quote(str(index))}, {lua_quote(path)}}},")
                lines.append("            },")
            lines.append("        },")
        lines.append("    },")
    lines.extend(["}", "", "return M", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--esmtool", required=True, type=pathlib.Path)
    parser.add_argument("--voice-esm", action="append", required=True, type=pathlib.Path)
    parser.add_argument("--race-esm", action="append", required=True, type=pathlib.Path)
    parser.add_argument("--data-root", action="append", default=[], type=pathlib.Path)
    parser.add_argument(
        "--sound-prefix",
        action="append",
        help="include Sound-relative paths with this prefix; repeat as needed (default: Vo\\)",
    )
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    races = collect_races(args.esmtool, args.race_esm)
    sound_prefixes = args.sound_prefix if args.sound_prefix is not None else ["Vo\\"]
    records = collect_voice_records(args.esmtool, args.voice_esm, races, sound_prefixes)
    if args.data_root:
        available_audio = audio_index(args.data_root)
        missing = sorted({path for _, _, _, path in records if path.replace("\\", "/").lower() not in available_audio})
        if missing:
            raise SystemExit("Voice records reference missing loose audio:\n  " + "\n  ".join(missing))
    if not records:
        raise SystemExit("No matching race voice records were found.")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.voice_esm, records), encoding="utf-8", newline="\n")
    matching_races = {race for race, _, _, _ in records}
    print(f"Generated {args.output}: {len(matching_races)} races, {len(records)} voice records")


if __name__ == "__main__":
    main()
