#!/usr/bin/env python3
"""Generate SHA-256 content-file rules from a published OpenMW Data Files directory."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


CONTENT_EXTENSIONS = {".esm", ".esp", ".omwgame", ".omwaddon", ".omwscripts"}


def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_content_list(path: Path) -> tuple[list[str], list[Path]]:
    names: list[str] = []
    data_dirs: list[Path] = []
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if "=" in line:
            key, value = line.split("=", 1)
            key = key.strip().casefold()
            value = unquote(value.strip())
            if key == "data":
                data_path = Path(value)
                if not data_path.is_absolute():
                    data_path = path.parent / data_path
                data_dirs.append(data_path.resolve())
                continue
            if key != "content":
                continue
            line = value
        else:
            line = unquote(line)
        if line:
            names.append(line)
    return names, data_dirs


def index_data_files(data_dirs: list[Path]) -> dict[str, Path]:
    files: dict[str, Path] = {}
    for data_dir in data_dirs:
        if not data_dir.is_dir():
            continue
        current_dir_files: dict[str, Path] = {}
        for path in data_dir.iterdir():
            if not path.is_file():
                continue
            key = path.name.casefold()
            if key in current_dir_files:
                raise ValueError(f"ambiguous case-insensitive filename in {data_dir}: {path.name}")
            current_dir_files[key] = path
        # OpenMW data directories are ordered from lowest to highest priority.
        files.update(current_dir_files)
    return files


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def lua_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{escaped}"'


def render_lua(entries: list[dict[str, str]], source: Path) -> str:
    lines = [
        "-- Generated by scripts/generate_mod_manifest.py; do not edit by hand.",
        f"-- Source directory: {source}",
        "return {",
    ]
    for entry in entries:
        lines.append(
            f"    {{ filename = {lua_string(entry['filename'])}, sha256 = {lua_string(entry['sha256'])} }},"
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Hash OpenMW content files and emit a Lua or JSON server manifest.",
        epilog=(
            "Example: python3 scripts/generate_mod_manifest.py '/srv/client/Data Files' "
            "--required Bardcraft.ESP --required Bardcraft.omwscripts -o mod_manifest.lua"
        ),
    )
    parser.add_argument("data_dir", type=Path, help="published client Data Files directory")
    parser.add_argument(
        "--required",
        action="append",
        default=[],
        metavar="FILENAME",
        help="include one required file; repeat to define required-file order",
    )
    parser.add_argument(
        "--content-list",
        type=Path,
        help=(
            "load filenames in order from openmw.cfg content= lines or a plain one-file-per-line list; "
            "existing data= directories are searched in OpenMW priority order"
        ),
    )
    parser.add_argument("--output", "-o", type=Path, default=Path("mod_manifest.lua"))
    parser.add_argument("--format", choices=("lua", "json"), help="default: inferred from output suffix")
    args = parser.parse_args()

    try:
        data_dir = args.data_dir.resolve(strict=True)
        if not data_dir.is_dir():
            raise ValueError(f"not a directory: {data_dir}")
        configured_names: list[str] = []
        configured_dirs: list[Path] = []
        if args.content_list:
            configured_names, configured_dirs = parse_content_list(args.content_list.resolve(strict=True))

        # Use the explicitly supplied published directory as a low-priority
        # fallback when it is not already represented by a data= entry.
        search_dirs = [data_dir, *configured_dirs]
        if args.required:
            names = args.required
        elif args.content_list:
            names = configured_names
        else:
            indexed_files = index_data_files(search_dirs)
            names = sorted(
                (path.name for path in indexed_files.values() if path.suffix.casefold() in CONTENT_EXTENSIONS),
                key=str.casefold,
            )

        indexed_files = index_data_files(search_dirs)

        if not names:
            raise ValueError("no content files selected")
        if len({name.casefold() for name in names}) != len(names):
            raise ValueError("the selected content list contains duplicate filenames")

        entries: list[dict[str, str]] = []
        for name in names:
            path = indexed_files.get(name.casefold())
            if path is None:
                searched = ", ".join(str(path) for path in search_dirs if path.is_dir())
                raise FileNotFoundError(f"content file not found in configured data directories: {name} (searched: {searched})")
            entries.append({"filename": path.name, "sha256": sha256_file(path)})

        output_format = args.format or ("json" if args.output.suffix.casefold() == ".json" else "lua")
        if output_format == "json":
            rendered = json.dumps({"requiredContentFiles": entries}, indent=2, ensure_ascii=False) + "\n"
        else:
            rendered = render_lua(entries, data_dir)

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(rendered.encode("utf-8"))
        print(f"Wrote {len(entries)} content-file SHA-256 entries to {args.output}")
        return 0
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
