param(
    [Parameter(Mandatory = $true)]
    [string] $InstallDir
)

$ErrorActionPreference = "Stop"

$installPath = (Resolve-Path -LiteralPath $InstallDir).Path
$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
New-Item -ItemType Directory -Force (Join-Path $installPath "Data Files") | Out-Null
New-Item -ItemType Directory -Force (Join-Path $installPath "userdata") | Out-Null

$manifest = [ordered]@{
    fallbackArchives = @("Morrowind.bsa", "Tribunal.bsa", "Bloodmoon.bsa")
    dataDirs = @("./Data Files")
    content = @("Morrowind.esm", "Tribunal.esm", "Bloodmoon.esm")
    userData = "./userdata"
}

$menuTextureSources = @(
    (Join-Path $installPath "resources\vfs\textures"),
    (Join-Path $repoRoot "files\data\textures")
)
$menuTextureDest = Join-Path $installPath "Data Files\textures"
New-Item -ItemType Directory -Force $menuTextureDest | Out-Null
foreach ($texture in @("menu_mainmenu.dds", "menu_mainmenu_over.dds", "menu_mainmenu_pressed.dds")) {
    $source = $menuTextureSources |
        ForEach-Object { Join-Path $_ $texture } |
        Where-Object { Test-Path -LiteralPath $_ } |
        Select-Object -First 1
    if ($source) {
        Copy-Item -LiteralPath $source -Destination (Join-Path $menuTextureDest $texture) -Force
    }
    else {
        Write-Warning "Could not find $texture in any known OpenMW texture source."
    }
}

$openmwCfg = Join-Path $installPath "openmw.cfg"
$existingLines = @()
if (Test-Path -LiteralPath $openmwCfg) {
    $existingLines = Get-Content -LiteralPath $openmwCfg
}

$portableKeysPattern = "^(config|replace|user-data|resources|data|data-local|content|fallback-archive)="
$preservedLines = @($existingLines | Where-Object { $_ -notmatch $portableKeysPattern })
$userConfigPath = Join-Path $installPath $manifest.userData
New-Item -ItemType Directory -Force $userConfigPath | Out-Null

$configLines = New-Object System.Collections.Generic.List[string]
$configLines.Add("# Portable Fetcher config generated by CI.")
$configLines.Add("# This file intentionally ignores Documents\My Games\OpenMW.")
$configLines.Add("replace=config")
$configLines.Add("user-data=$($manifest.userData)")
$configLines.Add("resources=./resources")
$configLines.Add("data=./resources/vfs-mw")
foreach ($dataDir in @($manifest.dataDirs)) {
    if ($dataDir) {
        $configLines.Add("data=$dataDir")
    }
}
foreach ($archive in @($manifest.fallbackArchives)) {
    if ($archive) {
        $configLines.Add("fallback-archive=$archive")
    }
}
foreach ($content in @($manifest.content)) {
    if ($content) {
        $configLines.Add("content=$content")
    }
}
$configLines.Add("")
if ($preservedLines.Count -gt 0) {
    $configLines.AddRange([string[]]$preservedLines)
}
Set-Content -LiteralPath $openmwCfg -Value $configLines -Encoding ASCII

$settingsLines = @(
    "# Portable Fetcher settings generated by CI.",
    "# This file intentionally ignores Documents\My Games\OpenMW.",
    "",
    "[Camera]",
    "viewing distance = 28672.0",
    "",
    "[Terrain]",
    "distant terrain = true",
    "object paging = true",
    "object paging active grid = true",
    "",
    "[Fog]",
    "use distant fog = false",
    "",
    "[Game]",
    "shield sheathing = true",
    "smooth animation transitions = true",
    "use additional anim sources = true",
    "weapon sheathing = true",
    "",
    "[Lua]",
    "lua profiler = false",
    "",
    "[Video]",
    "antialiasing = 16"
)
$settingsCfg = Join-Path $installPath "settings.cfg"
Set-Content -LiteralPath $settingsCfg -Encoding ASCII -Value $settingsLines

$userSettingsCfg = Join-Path $userConfigPath "settings.cfg"
Set-Content -LiteralPath $userSettingsCfg -Encoding ASCII -Value $settingsLines

$readmePath = Join-Path $installPath "PACKAGE_README.txt"
Set-Content -LiteralPath $readmePath -Encoding ASCII -Value @(
    "Fetcher Simulator clean base package",
    "",
    "This package is portable. It uses the openmw.cfg next to openmw.exe and intentionally ignores Documents\My Games\OpenMW\openmw.cfg.",
    "Writable config, logs, saves, screenshots, and generated user files are stored under .\userdata.",
    "Load order and content entries are stored directly in .\openmw.cfg so the package works without per-user OpenMW config.",
    "Portable graphics defaults are seeded in settings.cfg and .\userdata\settings.cfg. Launcher changes are saved to .\userdata\settings.cfg.",
    "This clean package intentionally excludes Fetcher updater tools and gameplay mods. To opt in, download Setup-Fetcher-Updater.bat from https://github.com/Skooma-Breath/Fetcher-Updater/releases/tag/fetcher-tester-tools."
)

Write-Output "Portable OpenMW config written to $openmwCfg."
Write-Output "Portable OpenMW settings written to $settingsCfg."
Write-Output "Portable OpenMW writable settings written to $userSettingsCfg."
