name: Release

on:
  push:
    branches:
      - main
    tags:
      - openmw-**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Ubuntu:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/ubuntu.yml
    with:
      image: ubuntu-24.04
      build-type: RelWithDebInfo
      package: true
      release: true
      release-tag: Fetcher-Simulator-Ubuntu
      release-name: Fetcher Simulator Ubuntu 24.04
      release-asset-name: fetcher-simulator-ubuntu-24.04-amd64.deb
    secrets: inherit

  Windows:
    uses: ./.github/workflows/windows.yml
    with:
      image: "2022"
      build-type: ${{ github.ref == 'refs/heads/main' && 'RelWithDebInfo' || 'Release' }}
      package: true
      release: true
      release-tag: ${{ github.ref == 'refs/heads/main' && 'Fetcher-Simulator' || '' }}
      release-name: ${{ github.ref == 'refs/heads/main' && 'Fetcher-Simulator' || '' }}
      release-zip-name: ${{ github.ref == 'refs/heads/main' && 'fetcher-simulator.zip' || '' }}
      release-include-installer: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit

  MacOS:
    strategy:
      fail-fast: true
      matrix:
        args:
          - image: macos-15
          - image: macos-15-intel
    uses: ./.github/workflows/macos.yml
    with:
      image: ${{ matrix.args.image }}
      build-type: Release
