name: Release

on:
  push:
    branches:
      - main
    tags:
      - openmw-**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Output-Envs:
    name: Read .env file and expose it as output
    runs-on: ubuntu-latest
    outputs:
      VCPKG_DEPS_TAG: ${{ env.VCPKG_DEPS_TAG }}
    steps:
      - uses: actions/checkout@v4
      - run: cat "${{ github.workspace }}/CI/github.env" >> $GITHUB_ENV

  Windows:
    needs:
      - Output-Envs
    uses: ./.github/workflows/windows.yml
    with:
      image: "2022"
      vcpkg-deps-tag: ${{ needs.Output-Envs.outputs.VCPKG_DEPS_TAG }}
      build-type: ${{ github.ref == 'refs/heads/main' && 'RelWithDebInfo' || 'Release' }}
      package: true
      release: true
      release-tag: ${{ github.ref == 'refs/heads/main' && 'Fetcher-Simulator' || '' }}
      release-name: ${{ github.ref == 'refs/heads/main' && 'Fetcher-Simulator' || '' }}
      release-zip-name: ${{ github.ref == 'refs/heads/main' && 'fetcher-simulator.zip' || '' }}
      release-include-installer: ${{ github.ref != 'refs/heads/main' }}
      mod-bundle-release-tag: ${{ github.ref == 'refs/heads/main' && 'openmw-client-mods-mp-clients' || '' }}
      mod-bundle-asset: openmw-client-mods.zip
    secrets: inherit
